version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo pre build
      - cdk --version
  build:
    commands:
      - npm install -g aws-cdk
      - cd ./backend && npm install && cdk synth && cdk deploy --require-approval never --all
      - echo $USER_POOL_ID
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - node_modules