version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo pre build
      - cdk --version
  build:
    commands:
      - npm uninstall -g aws-cdk && npm -g install aws-cdk
      - cd ./backend && npm install && cdk synth && cdk deploy --require-approval never --all
      - cd ../frontend/web && npm install && npm run build
      - cd ../provisioning && npm install && cdk deploy --all --require-approval never
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - node_modules